apiVersion: v1
kind: Secret
metadata:
  name: bugbounty-secrets
type: Opaque
stringData:
  MONGO_PASSWORD: "changeme"
  JWT_SECRET: "change-this-to-a-random-256-bit-string" # Deve ter 32+ chars
  ANTHROPIC_API_KEY: "sk-ant-coloque-sua-key-aqui"
  HACKERONE_API_USERNAME: "jackpach2084"
  HACKERONE_API_TOKEN: "FfSaYwK4vQdoQFg/6bWVgK8GUe+MHuL3Y2mZkF3p5s4="